[project]
name = "christats"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bambi>=0.16.0",
    "pandas>=2.3.3",
    "rpy2>=3.6.4",
    "seaborn>=0.13.2",
    "statsmodels>=0.14.5",
]
